export const metadata = {
  title: 'Investment Disclaimer - DVRG',
  description: 'DVRG investment disclaimer — important information about the limitations of AI-generated financial analysis.',
}

const LAST_UPDATED = 'February 19, 2026'

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-16">
      <div className="max-w-3xl mx-auto space-y-10">

        <div className="space-y-3">
          <h1 className="text-4xl font-bold text-text-primary">Investment Disclaimer</h1>
          <p className="text-sm text-text-tertiary">Last updated: {LAST_UPDATED}</p>
        </div>

        {/* Prominent warning */}
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-card p-6 space-y-3">
          <div className="flex items-center gap-3">
            <svg className="h-6 w-6 text-amber-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
            <h2 className="text-lg font-semibold text-amber-400">Not Financial Advice</h2>
          </div>
          <p className="text-sm text-amber-200/80 leading-relaxed">
            All content, analysis, reports, scores, price targets, and recommendations
            generated by DVRG are for <strong>informational and educational purposes only</strong>.
            Nothing on this platform constitutes professional financial, investment, legal,
            or tax advice. Do not make investment decisions based solely on DVRG output.
          </p>
        </div>

        <Section title="1. General Disclaimer">
          <p className="text-text-secondary text-sm leading-relaxed">
            DVRG is an AI-powered research tool that aggregates and analyzes publicly
            available financial data. The platform does not hold any securities licenses,
            is not a registered investment advisor (RIA), broker-dealer, or financial
            institution, and does not provide personalized investment advice.
          </p>
          <p className="text-text-secondary text-sm leading-relaxed mt-3">
            Any analysis, signal interpretation, structural valuation reference, price target, or
            investment thesis generated by DVRG is the output of automated AI models and
            does not reflect the judgment of a licensed financial professional.
          </p>
        </Section>

        <Section title="2. No Guarantee of Accuracy">
          <p className="text-text-secondary text-sm leading-relaxed">
            Financial data sourced from public providers (including but not limited to
            SEC filings, FINRA, yfinance, and news sources) may be delayed, incomplete,
            or contain errors. AI-generated analysis may produce incorrect, misleading,
            or outdated conclusions. DVRG makes no representations or warranties regarding
            the accuracy, completeness, or fitness for any particular purpose of any
            analysis output.
          </p>
        </Section>

        <Section title="3. Investment Risk">
          <p className="text-text-secondary text-sm leading-relaxed">
            Investing in securities involves significant risk, including the possible loss
            of all invested capital. Past performance of any stock, sector, or strategy
            does not guarantee or predict future results. Stock prices can and do move
            against the direction suggested by any analysis tool, including DVRG.
          </p>
          <p className="text-text-secondary text-sm leading-relaxed mt-3">
            Dark pool activity, institutional flow, insider transactions, and other signals
            analyzed by DVRG are historical and observable data points — they are not
            predictive guarantees of future price movements.
          </p>
        </Section>

        <Section title="4. AI Model Limitations">
          <p className="text-text-secondary text-sm leading-relaxed">
            DVRG uses large language models (LLMs) and quantitative algorithms that may
            produce hallucinated, biased, or incorrect output. LLM-generated text,
            including investment theses and risk assessments, should be treated as a
            starting point for further research, not a definitive conclusion.
          </p>
          <p className="text-text-secondary text-sm leading-relaxed mt-3">
            Signal scores, divergence ratings, and structural valuation references are model outputs
            based on heuristics and historical patterns. They are not audited financial
            calculations and may not reflect current market conditions.
          </p>
        </Section>

        <Section title="5. No Fiduciary Duty">
          <p className="text-text-secondary text-sm leading-relaxed">
            DVRG does not have a fiduciary duty to users. The platform does not take into
            account your personal financial situation, investment objectives, risk tolerance,
            tax status, or time horizon. Always consult a qualified financial advisor before
            making investment decisions.
          </p>
        </Section>

        <Section title="6. Forward-Looking Statements">
          <p className="text-text-secondary text-sm leading-relaxed">
            Any forward-looking statements, price targets, or strategic catalyst assessments
            in DVRG output involve known and unknown risks, uncertainties, and other factors
            that may cause actual results to differ materially from any future results
            expressed or implied. These statements are speculative and should not be
            relied upon as predictions.
          </p>
        </Section>

        <Section title="7. Third-Party Content">
          <p className="text-text-secondary text-sm leading-relaxed">
            DVRG may reference or summarize third-party news articles, analyst reports,
            or regulatory filings. Such references do not constitute endorsement of the
            source&apos;s views, and DVRG is not responsible for the accuracy of third-party content.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p className="text-text-secondary text-sm leading-relaxed">
            To the fullest extent permitted by law, DVRG shall not be liable for any
            investment losses, trading losses, or financial damages arising from your use
            of, or reliance on, any content or analysis provided by the platform.
          </p>
        </Section>

        <Section title="9. Contact">
          <p className="text-text-secondary text-sm leading-relaxed">
            Questions about this disclaimer? Contact us at{' '}
            <a href="mailto:support.dvrg.io@aigaai.com" className="text-primary hover:underline">
              support.dvrg.io@aigaai.com
            </a>.
          </p>
        </Section>

      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-4 pt-4 border-t border-surface-elevated">
      <h2 className="text-lg font-semibold text-text-primary">{title}</h2>
      {children}
    </div>
  )
}
