"""
Teaser digest — sends 7 ready-to-post social blurbs to the owner after each batch.

Triggered by the "batch/completed" event fired from weekly_batch.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ── Pure helpers (unit-tested) ───────────────────────────────────────────────

def format_teaser_blurb(signal: Any, base_url: str) -> str:
    """Format a single WeeklySignal into a ready-to-copy social media post."""
    ticker = signal.ticker
    verdict = (signal.verdict or "hold").capitalize()
    gap = signal.fairValueGapPct
    ev = signal.evProbability
    es = signal.esChangePct
    nq = signal.nqChangePct
    summary = signal.synthesisSummary or ""

    # Fair value line
    if gap is not None and gap > 0:
        value_line = f"{gap:.1f}% below fair value"
    elif gap is not None:
        value_line = f"{abs(gap):.1f}% above fair value"
    else:
        value_line = "fair value gap unavailable"

    # EV probability line
    ev_line = f"EV probability {int(ev * 100)}%" if ev is not None else ""

    # Market context line
    def _fmt_pct(label: str, val: Optional[float]) -> str:
        if val is None:
            return f"{label} n/a"
        sign = "+" if val >= 0 else ""
        return f"{label} {sign}{val:.1f}%"

    market_line = f"{_fmt_pct('ES', es)}, {_fmt_pct('NQ', nq)} this week."

    # Preview link
    preview_link = f"{base_url}/preview/{ticker.lower()}"

    parts = [f"{ticker} — {verdict}. {value_line}."]
    if summary:
        # Use first sentence of synthesis only to keep posts short
        first_sentence = summary.split(".")[0].strip()
        if first_sentence:
            parts[0] = f"{ticker} — {verdict}. {value_line} as {first_sentence.lower()}."
    if ev_line:
        parts.append(ev_line + ".")
    parts.append(market_line)
    parts.append(f"Full thesis → {preview_link}")

    return " ".join(parts)


def pick_top_signals(signals: List[Any], n: int) -> List[Any]:
    """
    Return the top n signals for the teaser digest.

    Prefers Buy verdicts. Falls back to all verdicts (sorted by screenerScore)
    if fewer than n Buy signals are available.
    """
    if not signals:
        return []

    buys = sorted(
        [s for s in signals if (s.verdict or "").lower() == "buy"],
        key=lambda s: (s.screenerScore or 0),
        reverse=True,
    )

    if len(buys) >= n:
        return buys[:n]

    # Not enough buys — top-up from all signals sorted by score
    all_sorted = sorted(signals, key=lambda s: (s.screenerScore or 0), reverse=True)
    seen = {s.ticker for s in buys}
    extras = [s for s in all_sorted if s.ticker not in seen]
    return (buys + extras)[: n]


def _build_email_html(blurbs: List[str], run_date: str, ticker_count: int) -> str:
    """Build the HTML body for the teaser digest email."""
    blurb_html = "".join(
        f"<div style='margin-bottom:24px;padding:16px;background:#f9f9f9;"
        f"border-left:4px solid #00D9B5;border-radius:4px;'>"
        f"<pre style='white-space:pre-wrap;font-family:monospace;font-size:13px;"
        f"margin:0;'>{blurb}</pre></div>"
        for blurb in blurbs
    )
    return f"""
<!DOCTYPE html>
<html>
<body style="font-family:sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#333">
  <h2 style="color:#00D9B5;margin-top:0">DVRG Weekly Teasers</h2>
  <p style="color:#666">Week of {run_date} &mdash; {ticker_count} stocks analyzed</p>
  <p>Copy and paste each blurb to X, Substack, or LinkedIn:</p>
  {blurb_html}
  <hr style="border:none;border-top:1px solid #eee;margin:24px 0">
  <p style="font-size:12px;color:#999">
    Auto-generated by DVRG weekly batch. Do not reply to this email.
  </p>
</body>
</html>
"""


# ── Inngest function ─────────────────────────────────────────────────────────
# Imported lazily so that the pure helper functions above can be unit-tested
# without the inngest pip package or runtime service dependencies present.

def _register_inngest_function():
    """Register the Inngest function. Called at module load only when the
    inngest client is importable (i.e. not during unit-test collection)."""
    from inngest.functions.analyze_stock import inngest  # noqa: PLC0415

    @inngest.create_function(
        fn_id="send-teaser-digest",
        trigger=inngest.trigger.event(event="batch/completed"),
        name="Send Teaser Digest",
        retries=2,
    )
    async def send_teaser_digest(ctx: Any, step: Any) -> Dict[str, Any]:
        """
        Send the owner a digest of 7 ready-to-post social blurbs after each batch.

        Triggered by the batch/completed event emitted by weekly_batch.
        """
        import resend  # noqa: PLC0415 — runtime-only dependency
        from api.lib.db import get_db  # noqa: PLC0415 — runtime-only dependency

        run_date_str: str = ctx.event.data["run_date"]
        ticker_count: int = ctx.event.data.get("ticker_count", 0)

        async def fetch_and_send() -> Dict[str, Any]:
            owner_email = os.getenv("OWNER_EMAIL", "")
            if not owner_email:
                logger.warning("OWNER_EMAIL is not set — skipping teaser digest")
                return {"status": "skipped", "reason": "OWNER_EMAIL not configured"}

            # Parse run_date from ISO string
            run_date = datetime.fromisoformat(run_date_str)

            db = await get_db()

            # Fetch all signals for this run_date
            signals = await db.weeklysignal.find_many(
                where={"runDate": run_date},
                order={"screenerScore": "desc"},
            )

            if not signals:
                logger.warning("No signals found for run_date=%s", run_date_str)
                return {"status": "skipped", "reason": "no_signals"}

            base_url = os.getenv("FRONTEND_URL", "https://dvrg.co")
            top = pick_top_signals(signals, n=7)
            blurbs = [format_teaser_blurb(s, base_url=base_url) for s in top]

            html_body = _build_email_html(
                blurbs=blurbs,
                run_date=run_date.strftime("%B %d, %Y"),
                ticker_count=ticker_count,
            )

            resend.api_key = os.getenv("RESEND_API_KEY", "")
            resend.Emails.send({
                "from": "DVRG Digest <digest@dvrg.co>",
                "to": [owner_email],
                "subject": f"DVRG Weekly Teasers — {run_date.strftime('%b %d, %Y')}",
                "html": html_body,
            })

            logger.info(
                "Teaser digest sent to %s with %d blurbs (run_date=%s)",
                owner_email, len(blurbs), run_date_str,
            )
            return {"status": "sent", "blurb_count": len(blurbs)}

        return await step.run("send-teaser-email", fetch_and_send)

    return send_teaser_digest


try:
    send_teaser_digest = _register_inngest_function()
except Exception:
    # inngest pip package not available (e.g. during unit tests) — no-op.
    send_teaser_digest = None  # type: ignore[assignment]
